### ISSUE TITLE
Log in and Sign up form are not prompting any errors when validating.

### ISSUE THREAD

**Issue by carlosgonzalez96** [osu-cascades/habit-loop#90]
If a user logs in with the wrong password or email the app is not displaying the error in some form.

**Comment by carlosgonzalez96** [comment]
Also if a user is creating a habit, theres no prompt when a form field is missed

**Comment by phelanjo** [comment]
I'll look into this one. It was working before, something must have broke.

**Comment by phelanjo** [comment]
I believe this has to do with this: https://github.com/osu-cascades/habit-loop/commit/cdf392722f59a1725f43d56d30c0b3501bce283c#diff-8a1bb7fa41ff26e6448deffad7023944L36

Before, we set the state of `error` to true if there was an incorrect username/password, which then displayed an error message on the login screen. With the refactor to use hooks, this functionality was lost.

**Comment by phelanjo** [comment]
Lol, nope. I'm just an idiot.

https://github.com/osu-cascades/habit-loop/commit/58ab7a6395e5fb0aeab902b5b3b62258e1e1b329

![image](https://user-images.githubusercontent.com/38761065/83067298-4a570700-a01b-11ea-9af7-adc56f877d15.png)

**Comment by phelanjo** [comment]
> Also if a user is creating a habit, theres no prompt when a form field is missed

I'm gonna move this one into it's own issue.

**Comment by phelanjo** [comment]
And I'm going to remove navigation to the Sign Up page for now, because it needs some work.

**Comment by phelanjo** [comment]
Issue resolved with: abd29149c79ad4cc58764f8415420168ac0a18ed
